### ISSUE TITLE
[Overview] Tracking of Remine API feature support

### ISSUE THREAD

**Issue by Art4** [kbsali/php-redmine-api#305]
I've looked through [Redmine's CHANGELOG](https://www.redmine.org/projects/redmine/wiki/Changelog) and gathered all the features that affect the REST API in this issue.

The goal is to have one place where Redmine features are captured and we can more easily see what functionality is not yet implemented.

### [Redmine 6.0.0](https://www.redmine.org/projects/redmine/wiki/Changelog_6_0)

- [ ] Feature [#23307](https://www.redmine.org/issues/23307): Include auth_source field in User API response
- [x] Feature [#38948](https://www.redmine.org/issues/38948): Add user status to users list API
- [ ] Feature [#40449](https://www.redmine.org/issues/40449): Add updated_on and updated_by fields to Issues API journal response

### [Redmine 5.1.0](https://www.redmine.org/projects/redmine/wiki/Changelog_5_1)

- [x] Feature [#37617](https://www.redmine.org/issues/37617): Add description field to custom fields API
- [x] Feature [#39113](https://www.redmine.org/issues/39113): Add missing Homepage attribute in Projects API response

### [Redmine 5.0.0](https://www.redmine.org/projects/redmine/wiki/Changelog_5_0)

- [ ] Feature [#35001](https://www.redmine.org/issues/35001): Disable API authentication with username and password when two-factor authentication is enabled for the user
- [ ] Feature [#10171](https://www.redmine.org/issues/10171): Updating journal notes via REST API
- [ ] Feature [#15855](https://www.redmine.org/issues/15855): Add information about whether an issue is open or closed to Issues API response
- [ ] Feature [#24976](https://www.redmine.org/issues/24976): Include new statuses allowed by workflow in Issues REST API
- [ ] Feature [#34766](https://www.redmine.org/issues/34766): Better error message when no API format is recognised
- [ ] Feature [#34857](https://www.redmine.org/issues/34857): Add total estimated hours, spent hours, total spent hours for issues to issue list API
- [x] Feature [#35420](https://www.redmine.org/issues/35420): API to archive/unarchive projects
- [ ] Feature [#35505](https://www.redmine.org/issues/35505): Add enabled core fields to /trackers API response
- [x] Feature [#35507](https://www.redmine.org/issues/35507): API to close/reopen projects
- [ ] Feature [#36303](https://www.redmine.org/issues/36303): Include avatar URL in Users API

### [Redmine 4.2.0](https://www.redmine.org/projects/redmine/wiki/Changelog_4_2)

- [ ] [Feature #22008](https://www.redmine.org/issues/22008): Associated Revision API
- [ ] [Feature #33301](https://www.redmine.org/issues/33301): Add option to include enabled issue custom fields in projects#show API response
- [ ] [Feature #33592](https://www.redmine.org/issues/33592): Include updated_on and passwd_changed_on columns in users API response
- [ ] [Feature #34242](https://www.redmine.org/issues/34242): Include two-factor authentication scheme in users API response

### [Redmine 4.1.0](https://www.redmine.org/projects/redmine/wiki/Changelog_4_1)

- [ ] [Feature #26237](https://www.redmine.org/issues/26237): Support wiki_page_title attribute in Versions REST API
- [ ] [Feature #30086](https://www.redmine.org/issues/30086): Use HTTP status code 403 instead of 401 when REST API is disabled
- [ ] [Feature #31559](https://www.redmine.org/issues/31559): Support "active" attribute in Enumerations REST API
- [ ] [Feature #32002](https://www.redmine.org/issues/32002): Add inherit_members to projects API response
- [ ] [Feature #32242](https://www.redmine.org/issues/32242): Add estimated hours and spent hours to Versions API
- [ ] [Patch #13468](https://www.redmine.org/issues/13468): REST API for News
- [ ] [Patch #31399](https://www.redmine.org/issues/31399): make /my/account endpoint accessible through API

### [Redmine 4.0.0](https://www.redmine.org/projects/redmine/wiki/Changelog_4_0)

- [ ] [Patch #28191](https://www.redmine.org/issues/28191): Add assignable, issues_visibility, time_entries_visibility and users_visibility to Roles API response
- [ ] [Patch #29459](https://www.redmine.org/issues/29459): Add admin flag to users API

### [Redmine 3.4.0](https://www.redmine.org/projects/redmine/wiki/Changelog_3_4)

- [ ] [Feature #7506](https://www.redmine.org/issues/7506): Include allowed activities list in "project" API response
- [x] [Feature #12181](https://www.redmine.org/issues/12181): Add attachment information to issues.xml in REST API
- [x] [Feature #23566](https://www.redmine.org/issues/23566): REST API should return attachment's id in addition to token
- [ ] [Patch #19116](https://www.redmine.org/issues/19116): Files REST API
- [x] #320
- [ ] [Patch #22795](https://www.redmine.org/issues/22795): Render custom field values of enumerations in API requests

### [Redmine 3.3.0](https://www.redmine.org/projects/redmine/wiki/Changelog_3_3)

- [x] [Feature #14830](https://www.redmine.org/issues/14830): REST API : Add support for attaching file to Wiki pages
- [x] [Feature #21757](https://www.redmine.org/issues/21757): Add Total spent hours and Estimated hours to the REST API response
- [x] [Patch #6277](https://www.redmine.org/issues/6277): REST API for Search

### [Redmine 3.0.0](https://www.redmine.org/projects/redmine/wiki/Changelog_3_0)

- [x] [Patch #18707](https://www.redmine.org/issues/18707): Allow attachment thumbnails from REST api

### [Redmine 2.6.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_6)

- [x] [Feature #17628](https://www.redmine.org/issues/17628): Expose project is_public property via API
- [x] [Patch #17602](https://www.redmine.org/issues/17602): Include enabled modules in projects API

### [Redmine 2.5.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_5)

- [x] [Feature #8842](https://www.redmine.org/issues/8842): REST API: Filter issues created/updated before or after specific timestamp
- [x] [Feature #15815](https://www.redmine.org/issues/15815): REST API : Add project status in API response

### [Redmine 2.4.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_4)

- [x] [Feature #11159](https://www.redmine.org/issues/11159): REST API for getting CustomField definitions
- [x] [Patch #13948](https://www.redmine.org/issues/13948): REST API should return user.status

### [Redmine 2.3.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_3)

- [x] [Feature #6727](https://www.redmine.org/issues/6727): Add/remove issue watchers via REST API
- [x] [Feature #8529](https://www.redmine.org/issues/8529): Get the API key of the user through REST API
- [x] [Patch #13155](https://www.redmine.org/issues/13155): Add login to /users/:id API for current user

### [Redmine 2.2.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_2)

- [x] [Feature #7082](https://www.redmine.org/issues/7082): Rest API for wiki
- [x] [Feature #9835](https://www.redmine.org/issues/9835): REST API - List priorities
- [x] [Feature #11502](https://www.redmine.org/issues/11502): Expose roles details via REST API
- [x] [Feature #11755](https://www.redmine.org/issues/11755): Impersonate user through REST API auth
- [x] [Feature #12125](https://www.redmine.org/issues/12125): Set filename used to store attachment updloaded via the REST API

### [Redmine 2.1.0](https://www.redmine.org/projects/redmine/wiki/Changelog_2_1)

- [x] [Feature #8981](https://www.redmine.org/issues/8981): REST Api for Groups

### [Redmine 1.4.0](https://www.redmine.org/projects/redmine/wiki/Changelog_1_4)

- [x] [Feature #7420](https://www.redmine.org/issues/7420): Rest API for projects members
- [x] [Feature #8171](https://www.redmine.org/issues/8171): Adding attachments through the REST API
- [x] [Feature #9803](https://www.redmine.org/issues/9803): Change project through REST API issue update
- [x] [Feature #10131](https://www.redmine.org/issues/10131): Include custom fiels in time entries API responses

### [Redmine 1.3.0](https://www.redmine.org/projects/redmine/wiki/Changelog_1_3)

- [x] [Feature #5737](https://www.redmine.org/issues/5737): Custom Queries available through the REST Api
- [x] [Feature #7180](https://www.redmine.org/issues/7180): List of statuses in REST API
- [x] [Feature #7181](https://www.redmine.org/issues/7181): List of trackers in REST API
- [x] [Feature #7366](https://www.redmine.org/issues/7366): REST API for Issue Relations
- [x] [Feature #7403](https://www.redmine.org/issues/7403): REST API for Versions
- [x] [Feature #7671](https://www.redmine.org/issues/7671): REST API for reading attachments
- [x] [Feature #9553](https://www.redmine.org/issues/9553): CRUD operations for "Issue categories" in REST API

### [Redmine 1.1.0](https://www.redmine.org/projects/redmine/wiki/Changelog_1_1)

- [x] [Feature #5338](https://www.redmine.org/issues/5338): Descendants (subtasks) should be available via REST API
- [x] [Feature #6140](https://www.redmine.org/issues/6140): REST issues response with issue count limit and offset
- [x] [Feature #6260](https://www.redmine.org/issues/6260): REST API for Users
- [x] [Feature #6779](https://www.redmine.org/issues/6779): Project JSON API
- [x] [Feature #6823](https://www.redmine.org/issues/6823): REST API for time tracker.
- [x] [Feature #7072](https://www.redmine.org/issues/7072): REST API for news
- [x] [Feature #7141](https://www.redmine.org/issues/7141): REST API: get information about current user

### [Redmine 1.0.0](https://www.redmine.org/projects/redmine/wiki/Changelog_1_0)

- [x] [Feature #1214](https://www.redmine.org/issues/1214): REST API for Issues

### [Redmine 0.9.0](https://www.redmine.org/projects/redmine/wiki/Changelog_0_9)

- [x] REST API for authentication
